-- MySQL Script generated by MySQL Workbench
-- 03/23/16 10:48:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema firends_recommend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema firends_recommend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `firends_recommend` DEFAULT CHARACTER SET utf8 ;
USE `firends_recommend` ;

-- -----------------------------------------------------
-- Table `firends_recommend`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firends_recommend`.`User` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `tw_user_id` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `screen_name` VARCHAR(45) NOT NULL,
  `location` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `description` VARCHAR(100) NULL,
  `profile_image_url` VARCHAR(45) NULL,
  `rcmd_user_ids` VARCHAR(100) NULL COMMENT 'split by \',\'',
  `since_id` VARCHAR(45) NULL,
  `max_id` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firends_recommend`.`Tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firends_recommend`.`Tweet` (
  `tweet_id` INT NOT NULL AUTO_INCREMENT,
  `tw_tweet_id` VARCHAR(45) NOT NULL,
  `text` VARCHAR(255) NULL,
  `user_id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `lang` VARCHAR(45) NULL,
  `coordinates` VARCHAR(45) NULL,
  PRIMARY KEY (`tweet_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `firends_recommend`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firends_recommend`.`FastSim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firends_recommend`.`FastSim` (
  `fastsim_id` INT NOT NULL AUTO_INCREMENT,
  `hash_id` VARCHAR(45) NOT NULL,
  `word_1` VARCHAR(45) NOT NULL,
  `word_2` VARCHAR(45) NOT NULL,
  `sim_wordnet` DECIMAL NULL,
  PRIMARY KEY (`fastsim_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firends_recommend`.`UserSim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firends_recommend`.`UserSim` (
  `usersim_id` INT NOT NULL AUTO_INCREMENT,
  `users_hash_id` VARCHAR(45) NOT NULL,
  `user1_id` INT NOT NULL,
  `user2_id` INT NOT NULL,
  `sim_1` DECIMAL NULL,
  PRIMARY KEY (`usersim_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `firends_recommend`.`Corpus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `firends_recommend`.`Corpus` (
  `corpus_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `word` VARCHAR(45) NOT NULL,
  `rate_1` DECIMAL NULL,
  PRIMARY KEY (`corpus_id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `firends_recommend`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
